travis:
  secure:
    BINSTAR_TOKEN: VULzo3+y7UHnbVVtnExv1MJ1npeE+SCVSTDQTHIw2XOsQzHYaTAI8s0+7sa1S5fimnA4/6D/GodFl9uMmj8upA5RlImXVfd1C7v3hDeYyY0ep+5h6Z5oniIr3Kut0DHYbWigoXpLpY5hOgx0L9Pp5SLzPBTLK5yajsiz9XdmX0OWXIU58+f9rzyh3N76T5HZoyP6IdkdVYkLzaQB5wjmSyjzvO5o1H+IidXC6gWEHklMmekjWjtRRVeqKc4byratKV3OpMCl/AI6D0ihxY44HWORrJ9tiY/Glu8QOFxDjE/hiW1YF+I32GEC6C9gPqVm3BE1AUGg7mdesGoKpGTVU9Gn06NBmc+ZgtBpfYY/qomR/MWI0AvQim+0jOh4s04mG2CyLi3YM0fDVuSKxhI8Su7WaNizKD1pexuAv5ev9LsqCulMA//1Ad0k7jYdrhz0LOq/3zjmN8/yllUnpsW1NQGqVA5z1vebRwxBOawBEiUbGiXrooMg+JfYxb/AuT0oxX/bLxY/uswZMOqyOF/A8koNbViryzyZTyfCoF6CDDuV9mAA59kVd/qGH2HCJXfeJGNXkuO2mNGqx7Lwad0ekeqr2+CVHe/poQeD+zWLV4QlAMi00n8U2SwSj/puXa6rwwu5lz3u287cshBRSt03LxgK8KFi8x4VJKfwH+f6US8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
