travis:
  secure:
    BINSTAR_TOKEN: pnifa5EUoYc0XKzRugrQ6fmivL4uwF22D2C2cs3tj7b6eNtZIYWVndnDKqVjvEqEJwt69ikQ7nzSkJNhdkyByOQuwlFjebude63q1MY65NQ9yrZf75NwKCVhWkWH7L80uQElUHKyGnT8LObZPNjWj48LEmBJMLBdeko1NgFETamvHGI2bAxmYo4fqxkbGVfuRtuZwZbVGiVGuUCaAFb5xMZLHZOhxp+K4rCUNzTQwdGXZ7bWaACxGzV0V8NMBDQlK4ltihppbCJUy9KBcWPVW9Tyrk4IotZObMwi6nnEWlXYfSmNxjQy0SPRYZ37Eg/ZhAYneQiXOLUD0eu8puH61aBQ3pTMs8LqlPz1ZoKdQtnq/9oDN4/lPtLq2YBZx1chfgQoiged1nlOtTjMzLrQfJqAkvhczArVJvhtotiZivrevGuNw9YpY3ZGJsmAU6lcZZi4TZrMIHajNuJ4VewQOFJkh6lhslQG668IgbN3x674vbMu0DuNfB0LNeMhuEy2W5wn3VQZTv4lHgPm6x1dcERup1n5WwW7bNASLw/qzta2++4a19dlevQmp/Jbu2stSMyjxg1LJKAIhZDShQdFP75hxqyPptxfczq5OtmlhLBBnO9Mz1TWLj7TkZ90P427bJFV5LhMiekg7tUryudlNpLUl8qfnXWFR8HbOZyRRUY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
